name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test on script Filesdeleter.sh
        run: |
          chmod +x TestFilesdeleter.sh 
          ./TestFilesdeleter.sh
